
# Job: Deploy
 deploy:
  runs-on: ubuntu-latest
 # Steps for the deploy job
  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to production
      run: echo "Deploying to production..."
